In [2]:
import pandas as pd
import numpy as np
import os
os.chdir(r'C:\L1K4\Data\네이버쇼핑')

In [ ]:
###

In [103]:
dt_galac = pd.read_csv("naver_date_galac.csv", index_col=0, names=["date"], header=0)
dt_galac

           date
0     21.02.14.
1     21.02.03.
2     20.12.29.
3     21.01.02.
4     21.01.02.
...         ...
1775  19.05.16.
1776  19.05.10.
1777  19.05.10.
1778  19.04.03.
1779  19.05.09.

[1780 rows x 1 columns]

In [37]:
pt_galac = pd.read_csv("naver_point_galac.csv", index_col=0, names=["point"], header=0)
pt_galac

      point
0         5
1         5
2         5
3         3
4         5
...     ...
2131      5
2132      5
2133      4
2134      5
2135      3

[2136 rows x 1 columns]

In [35]:
rw_galac = pd.read_csv("naver_review_galac.csv", index_col=0, names=["review"], header=0)
rw_galac

                                                 review
0                재구매하며 사용중인데\r\n각질없이 매끈한 피부로 유지되는거 같아요~
1                       계속 쓰고 있는데 펌프형 대용량이 나와서 너무 편하네요.
2     지인한테 좋다는 추천을 받아서 구매하게 되었는데 포장도 되게 꼼꼼히 해주시고 감사해...
3                    발효제품이나 얼굴에 촉촉하게 흡수가 빠르고 건조함이 덜 했어용
4                       초반엔 효과가 확 느껴졌는데 계속 쓰다보니 무난한거같아용
...                                                 ...
1775                                    개좋음;; 이거써보셍ㅎ 제발
1776                                       피부결 정돈하기 좋아요
1777                                 항상쓰는제품이예요~안쓰면 허전해서
1778  배송도 빠르고 같이 보내주신 마스크팩 사은품도 좋네요 예전에  타사의 제품을 써봐서...
1779                             촉촉한데요 건조하신 분한테는 좋을것같아요

[1780 rows x 1 columns]

In [123]:
rw_pt_galac = rw_galac.merge(pt_galac, left_index=True, right_index=True, how="left")
rw_pt_galac

                                                 review  point
0                재구매하며 사용중인데\r\n각질없이 매끈한 피부로 유지되는거 같아요~      5
1                       계속 쓰고 있는데 펌프형 대용량이 나와서 너무 편하네요.      5
2     지인한테 좋다는 추천을 받아서 구매하게 되었는데 포장도 되게 꼼꼼히 해주시고 감사해...      5
3                    발효제품이나 얼굴에 촉촉하게 흡수가 빠르고 건조함이 덜 했어용      3
4                       초반엔 효과가 확 느껴졌는데 계속 쓰다보니 무난한거같아용      5
...                                                 ...    ...
1775                                    개좋음;; 이거써보셍ㅎ 제발      4
1776                                       피부결 정돈하기 좋아요      5
1777                                 항상쓰는제품이예요~안쓰면 허전해서      5
1778  배송도 빠르고 같이 보내주신 마스크팩 사은품도 좋네요 예전에  타사의 제품을 써봐서...      5
1779                             촉촉한데요 건조하신 분한테는 좋을것같아요      3

[1780 rows x 2 columns]

In [127]:
rw_pt_dt_galac = rw_pt_galac.merge(dt_galac, left_index=True, right_index=True, how="left")
rw_pt_dt_galac.to_csv("rw_pt_dt_galac.csv", header=True, encoding="utf-8-sig")

In [107]:
def read_data(path1, path2, path3):
    dt = pd.read_csv(path1, index_col=0, names=["date"], header=0)
    rw = pd.read_csv(path2, names=["review"], header=0)
    pt = pd.read_csv(path3, index_col=0, names=["point"], header=0)

In [129]:
read_data(path1="naver_date_niasin.csv", path2="naver_review_niasin.csv", path3="naver_point_niasin.csv")

In [89]:
path = 'C:\L1K4\Data\네이버쇼핑'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.csv')]

In [119]:
review = []
columns = ["date", "point", "review"]

for x in range(16):
    path = 'C:/L1K4/Data/네이버쇼핑/naver_*_hi.csv'
    frame = pd.read_csv(path, names=columns)
    
    review.append(frame)

OSError: [Errno 22] Invalid argument: 'C:/L1K4/Data/네이버쇼핑/naver_*_hi.csv'

,Unnamed: 0,review,star,date
0,0,#사전체험단 일단 새롭게 바뀐 씨드세럼 너무 좋습니다!! 기존 씨드세럼하고 확실히 ...,5,2021.03.02
1,1,#사전체험단 업그레이드 되어 돌아왔음. 1. 뚜껑의 변화 대만족!!! 플라스틱 뚜껑...,5,2021.03.02
2,2,최근 속당김도 심하고 코 주변 살이 자주 터서 유분기 많은 크림을 발라야만 얼굴이 ...,5,2021.03.02
3,3,#사전체험단 체험단 신청해서 사용해보게됐어요^^ 받아왔는데 샘플 크기가 꽤 커서 놀...,5,2021.03.02
4,4,#사전체험단 그린티 씨드 세럼이 새로 리뉴얼 됐다는 소식 듣고 얼른 신청해보았습니다...,5,2021.03.02
...,...,...,...,...
4096,4096,#사전체험단 그린티 씨드 세럼 정말 7년째 써오고 있는 사람입니다. 일단 항상 세안...,5,2021.02.18
4097,4097,#사전체험단 초초 지성이고 볼은 언제나 홍조낀 붉은녀자입니다.ㅋㅋ 신제품 그린티씨드...,5,2021.02.18
4098,4098,#사전체험단 일단 속당김이 없고 피부에 잘 맞아서 좋아요! 씨드세럼 세통 정도 썼었...,5,2021.02.18
4099,4099,"#사전체험단 1. 향 : 기존대비 산뜻하고 맑아진 느낌이에요! 비온 뒤 맑은 날, ...",5,2021.02.18
4100,4100,#사전체험단 - 향 : ★★★★☆ : 구)형 비교 산뜻해졌고 무향도 좋을 것 같음 ...,5,2021.02.17